#!/usr/bin/php
<?php

$com   = $argv[1] ?? '';
$param = $argv[2] ?? '';
$sep   = DIRECTORY_SEPARATOR;

$syspath = getcwd() . $sep;
$r4path  = dirname(__FILE__) . $sep;

switch($com){
	case 'init':

		require $r4path .'utils/installer.php';

	break;
	case 'up':

		if($param == 'monitor') $monitor = true;
		require $r4path .'utils/compiler.php';

	break;

	case 'initmodule':

		$moduleName = $param;
		require $r4path .'utils/initmodule.php';

	break;
	default:
		echoc('Infome um comando para continuar...', 'yellow');
}


function echoc($msg='', $color='white') {
	echo $msg . PHP_EOL;
}